name: CI

on:
  push:
    branches: ['**']
  pull_request:
    branches: ['**']

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    # Use PostgreSQL service for database
    services:
      postgres:
        image: postgres:15
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: aidin_test
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 5432:5432

    env:
      CI: true
      DATABASE_URL: postgresql://postgres:postgres@localhost:5432/aidin_test?schema=public

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup Node.js 18.x
      uses: actions/setup-node@v4
      with:
        node-version: '18.x'
        cache: 'npm'

    - name: Prepare CI environment
      run: cp .env.ci .env.local

    - name: Install dependencies
      run: npm ci --legacy-peer-deps

    - name: Generate Prisma Client
      run: npx prisma generate

    - name: Setup PostgreSQL schema
      run: npx prisma db push --accept-data-loss

    - name: Run linter
      run: npm run lint --if-present

    - name: Build application
      run: npm run build
